name: test
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B install --file pom.xml

      - name: JaCoCo Code Coverage Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v5.0
        with:
          coverage_results_path: target/jacoco/jacoco.xml
          coverage_report_name: Coverage
          coverage_report_title: JaCoCo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: false
          minimum_coverage: 80
          fail_below_threshold: false
          publish_only_summary: false

      # Publish Coverage Job Summary  # Optional
      - name: Add Coverage Job Summary
        run: echo "${{ steps.jacoco_reporter.outputs.coverageSummary }}" >> $GITHUB_STEP_SUMMARY

      - name: Upload jacoco report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jacoco-report
          path: target/reports/jacoco
          retention-days: 1
      - name: Upload allure report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: target/reports/allure-report
          retention-days: 1

  deploy-reports:
    environment:
      name: github-pages
    outputs:
       report-url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: [ test ]
    if: always()
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - uses: actions/download-artifact@v4
        with:
          path: reports
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        if: always()
        with:
          name: github-pages
          path: reports
      - name: Setup Pages
        uses: actions/configure-pages@v4
        if: always()
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
        if: always()

  allure-report:
    runs-on: ubuntu-latest
    environment:
      name: allure-report
      url: ${{ needs.deploy-reports.outputs.report-url }}/allure-report
    needs: [ deploy-reports ]
    steps:
      - name: Add report url
        run: |
          echo "Allure Report:" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.deployment.outputs.page_url }}/allure-report" >> $GITHUB_STEP_SUMMARY
  coverage-report:
    runs-on: ubuntu-latest
    environment:
      name: coverage-report
      url: ${{ needs.deploy-reports.outputs.report-url }}/jacoco-report
    needs: [ deploy-reports ]
    steps:
      - name: Add report url
        run: |
          echo "Coverage Report:" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.deployment.outputs.page_url }}/jacoco-report" >> $GITHUB_STEP_SUMMARY